name: 'Compare Releases Across Repositories'
author: 'NickLiffen'
description: 'A GitHub Action which compares releasesa across two GitHub  '
inputs:
  destinationRepository:
    description: 'GitHub Repository of the Destination Repository. Format: Org/Repo'
    required: true
  sourceRepository:
    description: 'GitHub Repository of the Source Repository. Format: Org/Repo'
    required: true
  token:
    description: 'A repo scoped GitHub Personal Access Token'
    required: true
outputs:
  repo:
    description: 'The name of the repository with the newer release. Format: Org/Repo '
  tagName:
    description: 'The name of the tag on the destination repository. '
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'target'
  color: 'blue'
